---
title: "Wykaz częstotliwości występowania depresji u studentów"
author: "Norbert Dominkiewicz"
output: html_document
date: "`r Sys.Date()`"
---

# Biblioteki

```{r}
library(tidyverse)
library(scales)
library(psych)
library(moments)
library(DescTools)
```


# Wczytanie i przegląd danych
```{r}
dane <- read_csv("student_depression_dataset.csv")
head(dane)
```

# Wykresy

1.

```{r}
wykres1 <- dane[601:750, ] |>
  ggplot(aes(x = Age, y = after_stat(count) / sum(after_stat(count)))) +
  geom_bar(color = "brown", fill = "antiquewhite") +
  scale_y_continuous(labels = percent) +
  labs(title = "Rozkład wieku u studentów", x = "Wiek", y = "Odsetek badanych") +
  theme_bw() +
  theme(axis.text.y = element_text(angle = 25, color = "darkgreen"),
  plot.title = element_text(hjust = 0.5, color = "darkred"))

wykres1
```

2.

```{r}
wykres2 <- dane[401:550, ] |>
  ggplot(aes(x = `Study Satisfaction`, fill = Gender)) +
  geom_histogram(bins = 10, color = "black", position = "dodge") +
  labs(title = "Rozkład satysfakcji studentów u danej płci", x = "Poziom Satysfakcji", y = "Liczebność") +
  theme_bw() +
  theme(axis.text.y = element_text(angle = 25, color = "darkgreen"),
        plot.title = element_text(hjust = 0.5, color = "darkred"))

wykres2
```

3.

```{r}
wykres3 <- dane[801:950, ] |>
  group_by(`Sleep Duration`) |>
  summarise(count = n(), .groups = "drop") |>
  arrange(desc(count)) |>
  mutate(fraction = count / sum(count), ymax = cumsum(fraction), ymin = c(0, head(ymax, n = -1))) |>
  ggplot(aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = `Sleep Duration`)) +
  geom_rect(color = "white") +
  coord_polar(theta = "y") +
  xlim(c(2, 4)) +
  theme_void() +
  labs(title = "Czas snu studentów dla 150 rekordów",
       fill = "Sleep Duration") +
  scale_fill_brewer(palette = "Set2") +
  theme(plot.title = element_text(hjust = 0.5, color = "darkred", size = 14))

wykres3
```

# Parametry liczbowe i pozycyjne

<!-- Funkcja pomocnicza -->
Funkcja pomocnicza

```{r}
func <- function(tab) {
  print(paste("Mediana:", mean(tab)))
  print(paste("Wariancja:", var(tab)))
  print(paste("Odchylenie:", sd(tab)))
  print(paste("Rozstęp ćwiartkowy: ", IQR(tab)))
  print(paste("Kwartyle Q1 i Q3: "))
  print(paste(quantile(tab, probs = c(0.25,0.75))))
  print(paste("Minimum: ", min(tab)))
  print(paste("Maksimum: ", max(tab)))
  print(paste("Kurtoza: ", kurtosis(tab)))
  print(paste("Moda: ", Mode(tab)))
}
```


### 1. Wiek

```{r}
func(dane$Age)
```


### 2. Srednia ocen

```{r}
func(dane$CGPA)
```





